//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digiturkveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class paket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paket()
        {
            this.basvurus = new HashSet<basvuru>();
        }
    
        public int pid { get; set; }
        public int kid { get; set; }
        public int kateid { get; set; }
        public string padi { get; set; }
        public string purl { get; set; }
        public string paciklama { get; set; }
        public Nullable<bool> pdizi { get; set; }
        public Nullable<bool> pfilm { get; set; }
        public Nullable<bool> pspor { get; set; }
        public Nullable<bool> pmenuekle { get; set; }
        public string pinadi { get; set; }
        public string pinadi2 { get; set; }
        public string pinadi3 { get; set; }
        public string pinadi4 { get; set; }
        public string pinhiz { get; set; }
        public string pinhiz2 { get; set; }
        public string pinhiz3 { get; set; }
        public string pinhiz4 { get; set; }
        public string pinfiyat { get; set; }
        public string pinfiyat2 { get; set; }
        public string pinfiyat3 { get; set; }
        public string pinfiyat4 { get; set; }
        public string pkampdetay { get; set; }
        public Nullable<bool> pinternet { get; set; }
        public bool paktif { get; set; }
        public string pyazi { get; set; }
        public string paysayi { get; set; }
        public Nullable<bool> panasayfaekle { get; set; }
        public int prid { get; set; }
        public System.DateTime ptarih { get; set; }
        public string pfiyat { get; set; }
        public string pipadres { get; set; }
        public Nullable<bool> ptaraftar { get; set; }
        public string psenecekaciklama1 { get; set; }
        public string psenecekaciklama2 { get; set; }
        public string psenecekaciklama3 { get; set; }
        public string psenecekaciklama4 { get; set; }
        public string psenecekfiyat1 { get; set; }
        public string psenecekfiyat2 { get; set; }
        public string psenecekfiyat3 { get; set; }
        public string psenecekfiyat4 { get; set; }
        public string psenecekay1 { get; set; }
        public string psenecekay2 { get; set; }
        public string psenecekay3 { get; set; }
        public string psenecekay4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<basvuru> basvurus { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual paketResim paketResim { get; set; }
    }
}
