//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digiturkveri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Ayar
    {
        public int ayarid { get; set; }
        public int kid { get; set; }
        public string sitetel { get; set; }
        public System.DateTime ayartarih { get; set; }
        public string siteadi { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
